### ISSUE TITLE
Page file deleted, but drive letter unchanged

### ISSUE THREAD

**Issue by nofate301** [DdenBraver/xAzureTempDrive#1]
The configuration deployed successfully, but doesn't reboot the host, nor does it seem to set the temporary storage drive to X so the setting can activate.

If I view the win32_pagefilesetting wmi class it shows correctly it should be the X drive, but the setting never seems to apply.

**Comment by DdenBraver** [comment]
@nofate301 , could you please send me your part of the configuration so that I can run some tests?
Also please let me know what your current LCM settings are. Specifically your: ConfigurationMode, ActionAfterReboot, RebootNodeIfNeeded

**Comment by nofate301** [comment]
`Configuration TempDrive {
Import-DscResource -module xAzureTempDrive

Node localhost {

xAzureTempDrive AzureTempDrive #ResourceName
{
    DriveLetter = 'X'
}



}#Node

}TempDrive
`

We deallocated the host and brought it back online and it still didn't change.

**Comment by DdenBraver** [comment]
@nofate301 , I just ran the following configuration without any issue.
Could you please test it in your setup?

`
Configuration SetTempDrive {
    
    Import-DscResource -module xAzureTempDrive

    Node localhost {
        LocalConfigurationManager {
            ConfigurationMode = "ApplyandMonitor"
            RebootNodeIfNeeded = $true
        }
        xAzureTempDrive ChangeTempDrive
        {
            DriveLetter = 'Z'
        }
    }
}

SetTempDrive
Set-DscLocalConfigurationManager -Path '.\SetTempDrive'
Start-DscConfiguration -Path '.\SetTempDrive' -force -verbose -wait
`

If you are using any custom image, or anything has changed that may affect this behavior, please let me know so. In that case I might be able to work on a solution for that specific problem.

**Update: I ran this configuration on a Azure Marketplace Image for both Server 2012 R2 Datacenter, and Server 2016 Datacenter.

**Comment by nofate301** [comment]
Sure, I'll give it a wack and see what Azure spits back at me.

**Comment by nofate301** [comment]
Azure couldn't compile, but I was able to compile it locally and then upload the mof file.

The host rebooted shortly after application, but did not apply.  Image below shows the current state.

http://i.imgur.com/gZzyGRq.png?1

EDIT: also, this is a hub image from the azure marketplace and not custom.

**Comment by DdenBraver** [comment]
Hi @nofate301, sorry for not coming back to this earlier.
I think I may have found the issue, and have just pushed the new version to git.
Could you please check if this resolves your issue?

**Comment by nofate301** [comment]
I'll give it a shot, thanks for the help, and no worries about the delay.

**Comment by nofate301** [comment]
it works!  It rebooted the host and it works.  Thank you so much.

**Comment by DdenBraver** [comment]
Glad to hear! No problem at all :)

**Comment by DdenBraver** [comment]
Resolved with commit 57dadb3079dcdf25f145d05a8d784af71f691235
